#!/usr/bin/python3

import subprocess

filename = "tests/test00"

with open(filename, "r") as f:
    numbers = f.read().splitlines()
    for num in numbers:
        num = int(num)
    for i in range(2, int(num**0.5)+1):
        if num % i == 0:
            print(f"{num}={i}*{num//i}")
        break
    else:
        print(f"{num} is a prime number")
        subprocess.run(["sleep", "1"], timeout=1)
